### ISSUE TITLE
Erro when a shape is drawn.

### ISSUE THREAD

**Issue by Zagalillo** [jeremyk6/qdraw#17]
Hi Jeremy. 
Thanks for your plugin, is so useful.

An error is happening when a shape is drawn. The shape is actually drawn but after that, its properties can't be changed and also when the layer is erased the shape remains so the Qgis has to be closed and open again.

The error message is this:
```
2023-10-09T13:31:37     WARNING    Traceback (most recent call last):
File "C:\Users/ARQUITECTO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qdraw\qdraw.py", line 531, in draw             self.tool.reset()
File "C:\Users/ARQUITECTO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qdraw\drawtools.py", line 265, in reset
              self.rb.reset(True)
             TypeError: QgsRubberBand.reset(): argument 1 has unexpected type 'bool'
```
This is the version of Qgis I'm using:
![imagen](https://github.com/jeremyk6/qdraw/assets/46110763/9e6280fc-8f5f-49df-9f85-3ddaace26ee3)
If any other information is needed, please ask for it.
Thanks in advance.

**Comment by jeremyk6** [comment]
Hi. I just pushed a new version to the QGIS plugin repo with all fixes that have been submitted these last years. It should be available in a few hours/days. In the meantime, you can install the [ZIP file of the release](https://github.com/jeremyk6/qdraw/releases/tag/3.1).
