### ISSUE TITLE
I have Qgis Lima installed Qdraw gieve the folloing error

### ISSUE THREAD

**Issue by lion3k** [jeremyk6/qdraw#18]
TypeError: QgsRubberBand.reset(): argument 1 has unexpected type 'bool' 
Traceback (most recent call last):
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qdraw\qdraw.py", line 266, in drawRect
    self.tool = DrawRect(self.iface, self.settings.getColor())
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qdraw\drawtools.py", line 51, in __init__
    self.reset()
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qdraw\drawtools.py", line 57, in reset
    self.rb.reset(True)	 # true, its a polygon
TypeError: QgsRubberBand.reset(): argument 1 has unexpected type 'bool'

**Comment by lion3k** [comment]
When I try to use de rectangle tool.

**Comment by lion3k** [comment]
Hey, I just fix the problem with the solution posted by [Brigggi](https://github.com/Brigggi). Great community.

**Comment by jef-n** [comment]
> Hey, I just fix the problem with the solution posted by [Brigggi](https://github.com/Brigggi). Great community.

Please link the fix.   BTW this is a duplicate of #17
