### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ludovico85** [jeremyk6/qdraw#19]
Issue: when installing the plugin the following error appears:

```
TypeError: arguments did not match any overloaded call:   move(self, a0: QPoint): argument 1 has unexpected type 'float'   move(self, ax: int, ay: int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ludov/AppData/Roaming/QGIS/QGIS3\profiles\Ludovico_GIS/python/plugins\qdraw\__init__.py", line 22, in classFactory
    return Qdraw(iface)
           ^^^^^^^^^^^^
  File "C:\Users/ludov/AppData/Roaming/QGIS/QGIS3\profiles\Ludovico_GIS/python/plugins\qdraw\qdraw.py", line 78, in __init__
    self.settings = QdrawSettings()
                    ^^^^^^^^^^^^^^^
  File "C:\Users/ludov/AppData/Roaming/QGIS/QGIS3\profiles\Ludovico_GIS/python/plugins\qdraw\qdrawsettings.py", line 36, in __init__
    self.center()
  File "C:\Users/ludov/AppData/Roaming/QGIS/QGIS3\profiles\Ludovico_GIS/python/plugins\qdraw\qdrawsettings.py", line 81, in center
    self.move((screen.width() - size.width()) / 2,
TypeError: arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float''
```
QGIS version: 3.34.6

Python version: 3.12.3

**Note: the error can be solved by changing the qdrawsettings.py at line 81:**

Change

```python
self.move((screen.width() - size.width()) / 2,
          (screen.height() - size.height()) / 2)
```
To

```python
self.move(int((screen.width() - size.width()) / 2),
          int((screen.height() - size.height()) / 2))
```

**Comment by jeremyk6** [comment]
Hi. I just pushed a new version to the QGIS plugin repo with all fixes that have been submitted these last years. It should be available in a few hours/days. In the meantime, you can install the [ZIP file of the release](https://github.com/jeremyk6/qdraw/releases/tag/3.1).
