### ISSUE TITLE
Fehler ab Version  Python-Version: 3.12.5 | QGIS-Version: 3.34.10-Prizren

### ISSUE THREAD

**Issue by Roesslix** [jeremyk6/qdraw#20]
Konnte Erweiterung 'qdraw' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

TypeError: arguments did not match any overloaded call:   move(self, a0: QPoint): argument 1 has unexpected type 'float'   move(self, ax: int, ay: int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AKS4\AKS-QGIS-Konfig\qgis3\profiles\default/python/plugins\qdraw\__init__.py", line 22, in classFactory
    return Qdraw(iface)
           ^^^^^^^^^^^^
  File "D:\AKS4\AKS-QGIS-Konfig\qgis3\profiles\default/python/plugins\qdraw\qdraw.py", line 78, in __init__
    self.settings = QdrawSettings()
                    ^^^^^^^^^^^^^^^
  File "D:\AKS4\AKS-QGIS-Konfig\qgis3\profiles\default/python/plugins\qdraw\qdrawsettings.py", line 36, in __init__
    self.center()
  File "D:\AKS4\AKS-QGIS-Konfig\qgis3\profiles\default/python/plugins\qdraw\qdrawsettings.py", line 81, in center
    self.move((screen.width() - size.width()) / 2,
TypeError: arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'

Python-Version: 3.12.5 (main, Aug  8 2024, 11:21:54) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.10-Prizren Prizren, 113de9e1 

Python-Pfad:
C:/PROGRA~1/QGIS33~1.10/apps/qgis-ltr/./python
D:\AKS4\AKS-QGIS-Konfig\qgis3\profiles\default/python
D:\AKS4\AKS-QGIS-Konfig\qgis3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.10\apps\grass\grass84\etc\python
C:\Program Files\QGIS 3.34.10\bin
C:\Program Files\QGIS 3.34.10\bin\python312.zip
C:\PROGRA~1\QGIS33~1.10\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib
C:\PROGRA~1\QGIS33~1.10\apps\Python312
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages\Pythonwin
D:\AKS4\AKS-QGIS-Konfig\qgis3\profiles\default/python
D:/AKS4/GIS_Projekte/brwzonen/rwz_014ub210040
C:\Program Files\QGIS 3.34.10\bin

**Comment by tilmanb** [comment]
Is this a regression from #8 ?

**Comment by tilmanb** [comment]
There are more fixes in this commit in a fork from @LreeLenn https://github.com/jeremyk6/qdraw/compare/master...LreeLenn:qdraw:master

**Comment by jeremyk6** [comment]
Hi. I just pushed a new version to the QGIS plugin repo with all fixes that have been submitted these last years. It should be available in a few hours/days. In the meantime, you can install the [ZIP file of the release](https://github.com/jeremyk6/qdraw/releases/tag/3.1).
